trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  ToBeReplaced: replacement

steps:
- script: |
    echo $(System.DefaultWorkingDirectory)
    if exist $(System.DefaultWorkingDirectory)\config.json echo "found"


- task: FileTransform@2
  inputs:
    folderPath: $(System.DefaultWorkingDirectory)
    jsonTargetFiles: config.json
  displayName: 'Show failing FileTransform'
