trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  ToBeReplaced: replacement

steps:
- script: npm i -g pnpm@5.10.4
  displayName: Install pnpm

- script: pnpm i --frozen-lockfile
  displayName: Install deps

- task: FileTransform@2
  inputs:
    folderPath: $(System.DefaultWorkingDirectory)
    jsonTargetFiles: config.json
  displayName: Show failing FileTransform
