trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  ToBeReplaced: replacement

steps:
- task: FileTransform@1
  inputs:
    folderPath: $(System.DefaultWorkingDirectory)
    targetFiles: config.json
  displayName: 'Show failing FileTransform'
