trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  ToBeReplaced: replacement

steps:
- script: |
    npm install pnpm@5.10.4
    pnpm install --frozen-lockfile


- task: FileTransform@2
  inputs:
    folderPath: $(System.DefaultWorkingDirectory)
    jsonTargetFiles: config.json
  displayName: 'Show failing FileTransform'
